# Generated by Django 5.2.4 on 2025-08-04 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=10, verbose_name='Monto del Gasto')),
                ('date', models.DateField(help_text='Fecha del gasto', verbose_name='Fecha del Gasto')),
                ('description', models.TextField(blank=True, help_text='Descripción del gasto', null=True, verbose_name='Descripción del Gasto')),
                ('image', models.FileField(help_text='Imágen del gasto', upload_to='expense_images/', verbose_name='Imágen del Gasto')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del gasto', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del gasto', verbose_name='Fecha de Actualización')),
                ('is_paid', models.BooleanField(default=False, help_text='Indica si el gasto ha sido pagado', verbose_name='Gasto Pagado')),
                ('paid_date', models.DateField(blank=True, help_text='Fecha de pago del gasto', null=True, verbose_name='Fecha de Pago')),
                ('category', models.ForeignKey(help_text='Categoría del gasto', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Expenses.category', verbose_name='Categoría del Gasto')),
                ('created_by', models.ForeignKey(help_text='Usuario que Ingreso el gasto', on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
        ),
    ]
