# Generated by Django 5.2.4 on 2025-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], default='exit', help_text='Tipo de gasto', max_length=5, verbose_name='Tipo de Gasto'),
        ),
    ]
