# Generated by Django 5.2.4 on 2026-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.FileField(blank=True, help_text='Imágen del gasto', null=True, upload_to='expense_images/', verbose_name='Imágen del Gasto'),
        ),
    ]
